name: CI

on: [push]

jobs:

  Linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Build
      run: bin/package make
    - name: Regression tests
      run: |
        PS4="$PS4[ci.yml] "
        set -o xtrace
        export TZ=UTC
        ulimit -n 1024
        : default regression tests &&
        bin/shtests &&
        : regression tests with OS-provided UTF-8 locales &&
        LANG=nl_NL.UTF-8 bin/shtests --locale --nocompile &&
        LANG=ja_JP.UTF-8 bin/shtests --locale --nocompile &&
        : disable most SHOPTs, rebuild ksh &&
        sed --regexp-extended --in-place=.orig \
          '/^SHOPT (2DMATCH|AUDIT|BGX|BRACEPAT|DYNAMIC|EDPREDICT|ESH|FIXEDARRAY|HISTEXPAND|MULTIBYTE|NAMESPACE|OPTIMIZE|SUID_EXEC|STATS|VSH)=/ s/=1/=0/' \
          src/cmd/ksh93/SHOPT.sh &&
        bin/package make &&
        : default regression tests with SHOPTs disabled &&
        bin/shtests

  MacOS:
    name: macOS
    runs-on: macos-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Build
      run: bin/package make
    - name: Regression tests
      run: |
        PS4="$PS4[ci.yml] "
        set -o xtrace
        export TZ=UTC
        ulimit -n 1024
        : default regression tests &&
        bin/shtests &&
        : regression tests with OS-provided UTF-8 locales &&
        LANG=nl_NL.UTF-8 bin/shtests --locale --nocompile &&
        LANG=ja_JP.UTF-8 bin/shtests --locale --nocompile &&
        : disable most SHOPTs, rebuild ksh &&
        sed -E -i.orig \
          '/^SHOPT (2DMATCH|AUDIT|BGX|BRACEPAT|DYNAMIC|EDPREDICT|ESH|FIXEDARRAY|HISTEXPAND|MULTIBYTE|NAMESPACE|OPTIMIZE|SUID_EXEC|STATS|VSH)=/ s/=1/=0/' \
          src/cmd/ksh93/SHOPT.sh &&
        bin/package make &&
        : default regression tests with SHOPTs disabled &&
        bin/shtests
